# Generated by Django 4.1.4 on 2023-03-11 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0006_alter_season_options_remove_episode_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.FileField(upload_to='videos/movies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
    ]
