# Generated by Django 4.1.4 on 2023-03-11 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0007_alter_episode_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(upload_to='videos/movies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
        migrations.AlterField(
            model_name='series',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
    ]
