# Generated by Django 4.1.4 on 2023-03-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0010_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='mov.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(related_name='series_genre', to='mov.genre'),
        ),
    ]
