# Generated by Django 4.1.4 on 2023-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0011_alter_movie_genre_alter_series_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_genre', to='mov.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_genre', to='mov.genre'),
        ),
    ]
