# Generated by Django 4.1.4 on 2023-03-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0012_alter_movie_genre_alter_series_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_genre', serialize=False, to='mov.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='stars',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
