# Generated by Django 4.1.4 on 2023-03-11 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0013_alter_movie_genre_alter_movie_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.FileField(upload_to='videos/movies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='mov.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(upload_to='videos/movies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(to='mov.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv', 'vbmv'])]),
        ),
    ]
