# Generated by Django 4.1.4 on 2023-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0015_remove_movie_genre_remove_series_genre_delete_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
