# Generated by Django 4.1.4 on 2023-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0016_episode_duration_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
