# Generated by Django 4.1.4 on 2023-03-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0017_alter_episode_duration_alter_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
