# Generated by Django 4.1.4 on 2023-03-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0019_episode_duration_movie_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=19)),
            ],
        ),
    ]
