# Generated by Django 4.1.4 on 2023-03-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0020_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='typ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mov.type'),
            preserve_default=False,
        ),
    ]
